
# basic options
title: Dario Toman
author: Dario Toman
email: dario.toman@mail.utoronto.ca
github_username:  dariotoman
facebook_usernam:  dario.toman

# Build settings
markdown: kramdown
theme: minima